package com.eazyfreight.finance.service;

import com.eazyfreight.finance.domain.FinanceEnums.InvoiceStatus;
import com.eazyfreight.finance.domain.FinanceEnums.InvoiceType;
import com.eazyfreight.finance.domain.FinanceEnums.PaymentTermsType;

import com.eazyfreight.finance.domain.CustomerPayment;
import com.eazyfreight.finance.domain.FinanceEnums;
import com.eazyfreight.finance.domain.Invoice;
import com.eazyfreight.finance.domain.InvoiceLine;

import com.eazyfreight.common.pdf.PdfCanvas;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

/**
 * Renders a customer invoice to a PDF.
 *
 * <p>Only the sell side appears. The invoice aggregate carries buy and sell on every
 * line so that margin is a property of the record rather than a month-end
 * reconciliation, but the buy rate is what Eazy Freight pays the carrier and putting it
 * in front of the customer would hand them the negotiating position. The internal
 * screens show both; the document the customer receives shows one.
 *
 * <p>Rendered on demand rather than stored. An invoice's lines freeze when it is issued,
 * so the document is a pure function of the record — and a credit note is a separate
 * document rather than an edit to this one.
 */
@Component
public class InvoicePdfRenderer {

    private static final DateTimeFormatter DATE =
            DateTimeFormatter.ofPattern("d MMM yyyy").withZone(ZoneOffset.UTC);

    private static final String PROVENANCE =
            "SPECIMEN - generated by Eazy Freight for demonstration. Not a demand for "
                    + "payment and not a valid tax invoice.";

    public byte[] render(Invoice invoice) {
        try (PdfCanvas canvas = new PdfCanvas()) {
            canvas.footerOnEveryPage(PROVENANCE);

            header(canvas, invoice);
            terms(canvas, invoice);
            lines(canvas, invoice);
            payments(canvas, invoice);

            return canvas.toByteArray();
        }
    }

    public String fileName(Invoice invoice) {
        return invoice.getInvoiceNumber() + ".pdf";
    }

    private void header(PdfCanvas canvas, Invoice invoice) {
        canvas.line("EAZY FREIGHT INC", 15f, PdfCanvas.BOLD)
                .line(title(invoice.getInvoiceType()), 11f, PdfCanvas.REGULAR)
                .gap(4);

        canvas.text(invoice.getInvoiceNumber(), canvas.left(), 13f, PdfCanvas.MONO)
                .rightText(label(invoice.getStatus()),
                        canvas.left() + canvas.contentWidth(), 10f, PdfCanvas.BOLD)
                .gap(15);

        if (invoice.getStatus() == FinanceEnums.InvoiceStatus.VOIDED) {
            canvas.line("VOIDED - " + invoice.getVoidReason(), 9f, PdfCanvas.BOLD);
        }
        if (invoice.getStatus() == FinanceEnums.InvoiceStatus.PREPARED) {
            // A prepared invoice has not been issued to anyone. Saying so on the page
            // stops a draft that was downloaded for review being forwarded as a bill.
            canvas.line("DRAFT - not yet issued to the customer.", 9f, PdfCanvas.BOLD);
        }
        canvas.rule();
    }

    private void terms(PdfCanvas canvas, Invoice invoice) {
        canvas.heading("Invoice");
        canvas.fieldRow(
                "Invoice date", format(invoice.getInvoiceDate()),
                "Payment due", format(invoice.getPaymentDueDate()),
                "Terms", label(invoice.getPaymentTermsType()),
                "Currency", invoice.getCurrency());

        if (invoice.getPaymentTermsType() == FinanceEnums.PaymentTermsType.TWO_WEEKS_BEFORE_ARRIVAL
                && invoice.getConfirmedEta() != null) {
            canvas.paragraph(
                    "Payment falls due fourteen days before the vessel arrives on %s, so that "
                            .formatted(format(invoice.getConfirmedEta()))
                            + "settlement precedes release of the cargo.",
                    8.5f, PdfCanvas.REGULAR);
            canvas.gap(4);
        }
    }

    private void lines(PdfCanvas canvas, Invoice invoice) {
        canvas.heading("Charges");
        float[] widths = { canvas.contentWidth() - 250, -70, -80, -100 };
        canvas.row(8f, PdfCanvas.BOLD,
                new String[] { "DESCRIPTION", "QUANTITY", "RATE", "AMOUNT" }, widths);
        canvas.rule();
        canvas.gap(10);

        for (InvoiceLine line : invoice.getLines()) {
            canvas.row(9.5f, PdfCanvas.REGULAR, new String[] {
                    line.getDescription(),
                    "%s %s".formatted(strip(line.getQuantity()),
                            line.getUnit() == null ? "" : line.getUnit()).trim(),
                    money(line.getSellAmount(), invoice.getCurrency()),
                    money(line.extendedSell(), invoice.getCurrency()),
            }, widths);
        }

        canvas.gap(2).rule().gap(12);
        canvas.row(11f, PdfCanvas.BOLD, new String[] {
                "Total due", "", "", money(invoice.getTotalAmount(), invoice.getCurrency()),
        }, widths);

        if (invoice.getPaidAmount().signum() > 0) {
            canvas.row(9.5f, PdfCanvas.REGULAR, new String[] {
                    "Received", "", "", money(invoice.getPaidAmount(), invoice.getCurrency()),
            }, widths);
            canvas.row(11f, PdfCanvas.BOLD, new String[] {
                    "Outstanding", "", "",
                    money(invoice.outstandingAmount(), invoice.getCurrency()),
            }, widths);
        }
    }

    private void payments(PdfCanvas canvas, Invoice invoice) {
        if (invoice.getPayments().isEmpty()) {
            return;
        }
        canvas.heading("Payments received");
        float[] widths = { 130, 150, canvas.contentWidth() - 400, -120 };
        canvas.row(8f, PdfCanvas.BOLD,
                new String[] { "DATE", "METHOD", "REFERENCE", "AMOUNT" }, widths);
        canvas.rule();
        canvas.gap(9);
        for (CustomerPayment payment : invoice.getPayments()) {
            canvas.row(9f, PdfCanvas.REGULAR, new String[] {
                    format(payment.getPaymentDate()),
                    label(payment.getPaymentMethod()),
                    payment.getReference(),
                    money(payment.getAmount(), payment.getCurrency()),
            }, widths);
        }
    }

    // ------------------------------------------------------------------ helpers

    private static String title(FinanceEnums.InvoiceType type) {
        return switch (type) {
            case FREIGHT -> "Freight Invoice";
            case STORAGE_FEE -> "Storage Fee Invoice";
            case CREDIT_NOTE -> "Credit Note";
        };
    }

    private static String format(LocalDate date) {
        return date == null ? "-" : DATE.format(date.atStartOfDay(ZoneOffset.UTC));
    }

    private static String money(BigDecimal amount, String currency) {
        return amount == null ? "-" : "%s %,.2f".formatted(currency, amount);
    }

    /** 1.0000 reads as 1; 13.2000 reads as 13.2. */
    private static String strip(BigDecimal value) {
        return value == null ? "-" : value.stripTrailingZeros().toPlainString();
    }

    private static String label(Enum<?> value) {
        if (value == null) {
            return "-";
        }
        StringBuilder label = new StringBuilder();
        for (String word : value.name().split("_")) {
            label.append(label.isEmpty() ? "" : " ")
                    .append(word.charAt(0))
                    .append(word.substring(1).toLowerCase());
        }
        return label.toString();
    }
}
