package com.eazyfreight.documentation.service;

import com.eazyfreight.documentation.domain.DocumentationEnums.ReleaseType;

import com.eazyfreight.documentation.domain.DocumentationEnums;
import com.eazyfreight.documentation.domain.HouseBOL;

import com.eazyfreight.common.pdf.PdfCanvas;
import org.springframework.stereotype.Component;

import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;

/**
 * Renders a House Bill of Lading revision to a PDF.
 *
 * <p>Every value on the page comes from the {@link HouseBOL} revision itself, including
 * the party names and addresses, which the aggregate snapshots at issue precisely so a
 * document reprinted a year later still says what it said when it was issued. Nothing
 * here reaches back to the booking or the container.
 *
 * <p>That also makes rendering safe to do on demand rather than storing the bytes: a
 * revision is immutable once issued, and an amendment produces a new revision rather
 * than editing this one. The same input renders the same document every time.
 *
 * <p><strong>The document is marked as not negotiable.</strong> A real House BOL is a
 * document of title — whoever holds an original can claim the cargo. This one is
 * generated by a workshop system from invented data, so the footer says so on every
 * page and the header carries a specimen banner. Producing something that could be
 * mistaken for the real instrument is not a risk worth taking for a demonstration.
 */
@Component
public class HouseBOLPdfRenderer {

    private static final DateTimeFormatter DATE =
            DateTimeFormatter.ofPattern("d MMM yyyy").withZone(ZoneOffset.UTC);
    private static final DateTimeFormatter TIMESTAMP =
            DateTimeFormatter.ofPattern("d MMM yyyy HH:mm 'UTC'").withZone(ZoneOffset.UTC);

    private static final String NOT_NEGOTIABLE =
            "SPECIMEN - NOT NEGOTIABLE. Generated by Eazy Freight for demonstration. "
                    + "This is not a document of title and confers no right to any cargo.";

    public byte[] render(HouseBOL bol) {
        try (PdfCanvas canvas = new PdfCanvas()) {
            canvas.footerOnEveryPage(NOT_NEGOTIABLE);

            header(canvas, bol);
            parties(canvas, bol);
            carriage(canvas, bol);
            cargo(canvas, bol);
            release(canvas, bol);
            distribution(canvas, bol);

            return canvas.toByteArray();
        }
    }

    /** The filename the browser saves it under. */
    public String fileName(HouseBOL bol) {
        return "%s-rev%d.pdf".formatted(bol.getHouseBolNumber(), bol.getRevisionNumber());
    }

    private void header(PdfCanvas canvas, HouseBOL bol) {
        canvas.line("EAZY FREIGHT INC", 15f, PdfCanvas.BOLD)
                .line("House Bill of Lading", 11f, PdfCanvas.REGULAR)
                .gap(4);

        canvas.text(bol.getHouseBolNumber(), canvas.left(), 13f, PdfCanvas.MONO)
                .rightText("Revision %d".formatted(bol.getRevisionNumber()),
                        canvas.left() + canvas.contentWidth(), 10f, PdfCanvas.BOLD)
                .gap(15);

        if (!bol.isActive()) {
            canvas.line("SUPERSEDED - this revision has been replaced.", 9f, PdfCanvas.BOLD);
        }
        if (bol.getAmendmentReason() != null) {
            canvas.line("Amended: " + bol.getAmendmentReason(), 9f, PdfCanvas.REGULAR);
        }
        canvas.rule();
    }

    private void parties(PdfCanvas canvas, HouseBOL bol) {
        canvas.heading("Parties");
        canvas.fieldRow(
                "Shipper", join(bol.getShipperNameSnapshot(), bol.getShipperAddressSnapshot()),
                "Consignee", join(bol.getConsigneeNameSnapshot(), bol.getConsigneeAddressSnapshot()));
        canvas.fieldRow(
                "Notify party",
                join(bol.getNotifyPartyNameSnapshot(), bol.getNotifyPartyAddressSnapshot()),
                "Freight terms", label(bol.getFreightTerms()));
    }

    private void carriage(PdfCanvas canvas, HouseBOL bol) {
        canvas.heading("Carriage");
        canvas.fieldRow(
                "Vessel", bol.getVesselName(),
                "Voyage", bol.getVoyageNumber(),
                "Port of loading", bol.getPortOfLoadingCode(),
                "Port of discharge", bol.getPortOfDischargeCode());
    }

    private void cargo(PdfCanvas canvas, HouseBOL bol) {
        canvas.heading("Cargo");
        canvas.fieldRow(
                "Container", bol.getContainerNumber(),
                "Seal", bol.getSealNumber(),
                "HS code", bol.getHsCode());

        float[] widths = { canvas.contentWidth() - 240, -80, -80, -80 };
        canvas.row(8f, PdfCanvas.BOLD,
                new String[] { "DESCRIPTION OF GOODS", "PIECES", "GROSS WEIGHT", "MEASUREMENT" },
                widths);
        canvas.rule();
        canvas.gap(10);
        canvas.row(9.5f, PdfCanvas.REGULAR, new String[] {
                bol.getCargoDescription(),
                bol.getPieces() == null ? "-" : String.valueOf(bol.getPieces()),
                bol.getWeightKg() == null ? "-" : strip(bol.getWeightKg()) + " kg",
                bol.getCbm() == null ? "-" : strip(bol.getCbm()) + " CBM",
        }, widths);

        if (bol.getMarksAndNumbers() != null && !bol.getMarksAndNumbers().isBlank()) {
            canvas.gap(4);
            canvas.fieldRow("Marks and numbers", bol.getMarksAndNumbers());
        }
    }

    private void release(PdfCanvas canvas, HouseBOL bol) {
        canvas.heading("Release");
        canvas.fieldRow(
                "Release type", label(bol.getReleaseType()),
                "Issued", bol.getIssuedAt() == null ? "-" : TIMESTAMP.format(bol.getIssuedAt()),
                "Issued by", bol.getIssuedBy());

        // Only ORIGINAL_BOL produces negotiable paper, and only then does surrender
        // matter. Printing "0 of 0 surrendered" against a telex release invites someone
        // to go looking for documents that were never issued.
        bol.originals().ifPresent(originals -> canvas.fieldRow(
                "Originals issued", String.valueOf(originals.getOriginalsIssued()),
                "Surrendered", String.valueOf(originals.getOriginalsSurrendered()),
                "Released to", originals.getReleasedTo(),
                "Courier reference", originals.getCourierReference()));

        canvas.gap(4).paragraph(describe(bol.getReleaseType()), 8.5f, PdfCanvas.REGULAR);
    }

    private void distribution(PdfCanvas canvas, HouseBOL bol) {
        if (bol.getDistributions().isEmpty()) {
            return;
        }
        canvas.heading("Distribution");
        float[] widths = { 150, 150, canvas.contentWidth() - 430, 130 };
        canvas.row(8f, PdfCanvas.BOLD,
                new String[] { "RECIPIENT", "NAME", "CHANNEL", "SENT" }, widths);
        canvas.rule();
        canvas.gap(9);
        bol.getDistributions().forEach(distribution -> canvas.row(9f, PdfCanvas.REGULAR,
                new String[] {
                        label(distribution.getRecipient()),
                        distribution.getRecipientName(),
                        label(distribution.getChannel()),
                        DATE.format(distribution.getSentAt()),
                }, widths));
    }

    // ------------------------------------------------------------------ helpers

    private static String join(String name, String address) {
        if (name == null) {
            return "-";
        }
        return address == null || address.isBlank() ? name : name + ", " + address;
    }

    /** 8340.500 reads as 8340.5; 13.2000 as 13.2. Trailing zeros are noise on paper. */
    private static String strip(java.math.BigDecimal value) {
        return value.stripTrailingZeros().toPlainString();
    }

    private static String label(Enum<?> value) {
        if (value == null) {
            return "-";
        }
        String[] words = value.name().split("_");
        StringBuilder label = new StringBuilder();
        for (String word : words) {
            label.append(label.isEmpty() ? "" : " ")
                    .append(word.charAt(0))
                    .append(word.substring(1).toLowerCase());
        }
        return label.toString();
    }

    /** What the release type actually obliges the parties to do. */
    private static String describe(DocumentationEnums.ReleaseType releaseType) {
        if (releaseType == null) {
            return "";
        }
        return switch (releaseType) {
            case ORIGINAL_BOL -> "Three negotiable originals have been issued. One must be "
                    + "surrendered at destination before the cargo is released.";
            case TELEX_RELEASE -> "The shipper has surrendered their claim electronically. "
                    + "No original bill has been issued and none is required at destination.";
            case SEA_WAYBILL -> "Non-negotiable. The named consignee collects on proof of "
                    + "identity; no document needs to travel.";
        };
    }
}
